-- depends:

CREATE TABLE IF NOT EXISTS powers (
    power_id INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title    VARCHAR(100) NOT NULL,

    CONSTRAINT uq_powers_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS hero (
    client_uuid UUID         PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    image       BYTEA
);

INSERT INTO powers (title) VALUES
    ('Super Strength'),
    ('Flight'),
    ('Super Speed'),
    ('Невидимость'),
    ('Огненные шары'),
    ('Телепортация'),
    ('Телепатия'),
    ('Регенерация'),
    ('Управление временем'),
    ('Лазерные глаза'),
    ('Супер-интеллект'),
    ('Неуязвимость'),
    ('Управление погодой'),
    ('Чтение мыслей')
ON CONFLICT (title) DO NOTHING;
