-- depends:

CREATE TABLE IF NOT EXISTS roles (
    role_id   INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50)  NOT NULL,

    CONSTRAINT uq_roles_role_name UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS client (
    client_uuid UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    pass_hash   VARCHAR(255) NOT NULL,
    role_id     INT          NOT NULL,
    email       VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_client_role
        FOREIGN KEY (role_id) REFERENCES roles (role_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_client_role_email UNIQUE (role_id, email)
);

INSERT INTO roles (role_name) VALUES
    ('hero'),
    ('corporation')
ON CONFLICT DO NOTHING;
